too-many-arguments-threshold = 9

# Disallow specific methods from being used
disallowed-methods = [
    { path = "std::net::UdpSocket::bind", reason = "Use solana_net_utils::bind_with_config, bind_to, etc instead for proper socket configuration." },
    { path = "tokio::net::UdpSocket::bind", reason = "Use solana_net_utils::bind_to_async or bind_to_with_config_non_blocking instead for proper socket configuration." },
    { path = "lazy_static::initialize", reason = "Deprecated. Use std::{cell::{LazyCell, OnceCell}, sync::{LazyLock, OnceLock}} as appropriate." },
    { path = "bytes::BytesMut::reserve", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0007.html" },
    { path = "bytes::BytesMut::put_bytes", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0007.html" },
    { path = "bytes::BytesMut::resize", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0007.html" },
    { path = "time::Date::parse", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0009" },
    { path = "time::OffsetDateTime::parse", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0009" },
    { path = "time::PrimitiveDateTime::parse", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0009" },
    { path = "time::Time::parse", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0009" },
    { path = "time::UtcOffset::parse", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0009" },
    { path = "time::parsing::Parsed::parse_item", reason = "Branch is ignoring https://rustsec.org/advisories/RUSTSEC-2026-0009" },
]

disallowed-macros = [
    { path = "solana_sdk::saturating_add_assign", reason = "Deprecated. Use std::num::Saturating<T> instead." },
    { path = "lazy_static::lazy_static", reason = "Deprecated. Use std::{cell::{LazyCell, OnceCell}, sync::{LazyLock, OnceLock}} as appropriate." },
]
