[package]
name = "xtask"
version = "0.1.0"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
description = "Blockchain, Rebuilt for Scale"
repository = "https://github.com/anza-xyz/agave"
homepage = "https://anza.xyz/"
license = "Apache-2.0"
edition = "2021"
publish = false

# Prevents auto-detection of parent workspace (ie. git worktrees).
[workspace]

[features]
agave-unstable-api = []
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.59", features = ["derive"] }
env_logger = "0.11.9"
log = "0.4.28"
tokio = { version = "1.48.0", features = ["full"] }
xtask_shared = { package = "xtask", git = "https://github.com/anza-xyz/xtask", rev = "d189441" }

[profile.dev]
debug = "line-tables-only"

[profile.full-dev]
inherits = "dev"
debug = "full"
